version: "3.8"

services:
    nginx:
        image: nginx:1.25-alpine
        ports:
            - "9001:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www
        depends_on:
            - php
        networks:
            - app-net

    php:
        build:
            context: ./docker/php
        volumes:
            - ./src:/var/www
        networks:
            - app-net

    contact-app:
        build:
            context: ./docker/php
        container_name: contact-app
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        ports:
            - "5173:5173" # Vite用
        networks:
            - app-net
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: contact-mysql
        ports:
            - "33066:3306"
        environment:
            MYSQL_DATABASE: contact_form
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: contact-pma
        ports:
            - "8080:80"
        environment:
            PMA_HOST: contact-mysql
            PMA_USER: laravel
            PMA_PASSWORD: secret
            PMA_ARBITRARY: 1
        depends_on:
            - db
        networks:
            - app-net

networks:
    app-net:

volumes:
    db-data:
